# -*- coding: utf-8 -*-
"""streamlit_dep.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WyGB4O-PypR697IDNXS9xrU6M_gOZza0
"""

pip install streamlit

pip install Writefile

# Commented out IPython magic to ensure Python compatibility.
# %%writefile st.py
# import streamlit as st
# 
# st.write("Hello World")



! wget -q -O - ipv4.icanhazip.com

! streamlit run st.py & npx localtunnel --port 8501



st.write("Hello World")